version: '3.8'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb_container
    environment:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  mongodb_network:

volumes:
  mongodb_data:
    driver: local
