version: '3'

services:
  postgres:
    image: postgres:13.4
    container_name: worktime-postgres-db
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - worktime

volumes:
  postgres_data:

networks:
  worktime:
    driver: bridge  # Specify the network driver, can be bridge, overlay, etc.
